trigger: none
pool:
  name: devopsagent-vm  # Custom agent pool for your VM

variables:
  # Set your environment variables for the username, private key, and public IP securely
  vmUsername: 'azureuser'  # Replace with your actual VM username
  vmPrivateKey: $(vmPrivateKey)  # Store private SSH key in Azure Pipeline secrets
  vmPublicIp: '20.68.0.124'  # Replace with the public IP of your VM

stages:
  - stage: Build
    displayName: Build stage
    jobs:  
      - job: Build
        displayName: Build
        steps:
        - task: UseNode@1
          inputs:
            version: '16.x'  # Install Node.js version 16.x
          displayName: 'Install Node.js'
        - script: |
            npm install
            npm run build --if-present  # Optional: Only if you have a build script
            npm run test --if-present    # Optional: Only if you have a test script
          displayName: 'npm install, build and test'
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'  # Path to the working directory
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip  # Store as .zip
            replaceExistingArchive: true
        - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip  # Upload artifact
          artifact: drop  # Artifact name for later use


  - stage: Deploy
    displayName: 'Deploy Node.js Application'
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        steps:
          - task: UseNode@1
            inputs:
              version: '16.x'
            displayName: 'Install Node.js'

          - script: |
              echo "Starting deployment on VM..."
              mkdir -p ~/.ssh  # Ensure the .ssh directory exists
              echo "$(vmPrivateKey)" > ~/.ssh/id_rsa  # Write the private key to a file
              chmod 600 ~/.ssh/id_rsa  # Ensure the key has the correct permissions
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $(vmUsername)@$(vmPublicIp) "mkdir -p /home/$(vmUsername)/app"
              scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r "$(Build.SourcesDirectory)" $(vmUsername)@$(vmPublicIp):/home/$(vmUsername)/app
            displayName: 'Copy files to VM via SCP'

          - script: |
              echo "Running deployment commands on the remote VM..."
              ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $(vmUsername)@$(vmPublicIp) <<EOF
                cd /home/$(vmUsername)/app
                npm install
                npm run build
                npm run start
              EOF
            displayName: 'Run deployment commands on VM'






        

                       
          
